### ISSUE TITLE
[SUPPORT] Need to make font size bigger, but i'm lost

### ISSUE THREAD

**Issue by Fischje** [flixlix/flixlix-cards#145]
My card is very small on my tablet-dashboard. I want to make the font bigger but i can't get it working. Any support?

**Comment by designer2k2** [comment]
with card-mod installed, add this to your power-flow-card-plus card:
```yaml
card_mod:
  style: |
    ha-card .label {
      font-size: 14px !important;
      font-weight: normal !important;
    }
    ha-card .circle {
      font-size: 16px !important;
      font-weight: bold !important;
    }
```
