### ISSUE TITLE
[BUG] individual max devices?

### ISSUE THREAD

**Issue by texta83** [flixlix/flixlix-cards#156]
With the new version, I have now added 16 individual devices. Unfortunately, it no longer shows the top 4 devices from the old ones. For example, when I move position 16 to position 10, it shows up in the top 4. So not all positions are being considered, or rather, only a maximum number is taken into account.

How is it on your end?

**Comment by andbad** [comment]
I think I have a similar problem.
This is the configuration:

```
type: custom:power-flow-card-plus
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.75
max_flow_rate: 10
watt_threshold: 1100
clickable_entities: true
title: Potenza
use_new_flow_rate_model: true
min_expected_power: 1
max_expected_power: 5000
display_zero_lines:
  mode: transparency
  transparency: 85
  grey_color:
    - 189
    - 189
    - 189
entities:
  grid:
    icon: hass:transmission-tower
    name: Rete
    display_state: one_way
    color_value: false
    invert_state: false
    display_zero_tolerance: 30
    entity:
      consumption: sensor.potenza_prelievo
      production: sensor.potenza_immissione
    color_circle: true
    color_icon: true
  solar:
    icon: hass:solar-panel-large
    entity: sensor.potenza_fotovoltaico
    color_value: false
    color_icon: true
  battery:
    name: Batteria
    display_state: one_way
    state_of_charge: sensor.soc_accumulo
    entity:
      consumption: sensor.potenza_prelievo_accumulo
      production: sensor.potenza_immissione_accumulo
    color_value: false
    state_of_charge_unit_white_space: false
  individual:
    - entity: sensor.potenza_frigorifero
      name: Frigorifgero
      icon: hass:fridge-variant-outline
      secondary_info: {}
      display_zero_tolerance: 15
    - entity: sensor.potenza_hal
      name: HAL
      icon: hass:nas
      secondary_info:
        entity: sensor.system_monitor_processor_use
        unit_of_measurement: "%"
        display_zero: false
        icon: mdi:cpu-64-bit
      display_zero: false
      display_zero_state: false
    - entity: sensor.potenza_presabagno
      name: Stufetta
      icon: hass:radiator
      display_zero_tolerance: 5
    - entity: sensor.potenza_microonde
      name: Microonde
      icon: hass:microwave
      display_zero_tolerance: 5
    - entity: sensor.potenza_friggitrice
      name: Friggitrice
      icon: hass:french-fries
      display_zero_tolerance: 5
    - entity: sensor.potenza_forno
      name: Forno
      icon: hass:stove
      display_zero_tolerance: 5
    - entity: sensor.potenza_lavastoviglie
      name: Lavastoviglie
      icon: hass:dishwasher
      secondary_info: {}
      display_zero_tolerance: 5
    - entity: sensor.potenza_condizionatoreingresso
      name: Condizionatore Ingresso
      icon: hass:air-conditioner
      secondary_info: {}
      display_zero_tolerance: 5
    - entity: sensor.potenza_condizionatorecamera
      name: Condizionatore Camera
      icon: hass:air-conditioner
      secondary_info: {}
      display_zero_tolerance: 5
    - entity: sensor.potenza_lavatrice
      name: Lavatrice
      icon: hass:washing-machine
      secondary_info: {}
      display_zero_tolerance: 5
    - entity: sensor.potenza_leaf_combinata
      name: Leaf
      icon: hass:car-electric
      secondary_info:
        entity: sensor.leaf1andb_charge
        unit_of_measurement: "%"
        display_zero: true
      display_zero: true
    - entity: sensor.potenza_ts
      name: TS
      icon: hass:motorbike-electric
      display_zero_tolerance: 5
    - entity: sensor.potenza_boiler
      name: Boiler
      icon: hass:water-boiler
      secondary_info: {}
      display_zero_tolerance: 5
    - entity: sensor.potenza_induzione
      name: Induzione
      icon: hass:fire
      display_zero_tolerance: 5
    - entity: sensor.potenza_pdc
      name: PdC
      icon: hass:heat-pump
      secondary_info:
        entity: sensor.pdc_temperatura_termostato_acqua
        unit_of_measurement: " °C"
        unit_white_space: true
      display_zero_tolerance: 10
    - entity: sensor.potenza_presabagnokevin
      name: Stufetta Kevin
      icon: hass:radiator
      display_zero_tolerance: 5
    - entity: sensor.potenza_totale_luci
      name: Luci
      icon: hass:lightbulb-multiple
      secondary_info: {}
      display_zero_tolerance: 17
  home:
    entity: sensor.potenza_totale
    color_icon: true
    subtract_individual: true
    color_circle: consumption
    override_state: false
  fossil_fuel_percentage:
    entity: sensor.electricity_maps_percentuale_della_rete_di_combustibili_fossili
    icon: hass:pine-tree
    color_icon: true
    display_zero: true
    name: Green
    state_type: percentage
    unit_white_space: false
    use_metadata: false
dashboard_link: ""
disable_dots: false
sort_individual_devices: true

```

![Image](https://github.com/user-attachments/assets/ecf60b8c-ff0a-42e6-9f98-97e267ea6473)

sensor.potenza_hal has 13W value. If I put it in the first position, it does not show up (even if there are no other individual devices), if as in the example I put it in the second position, it does show up.
Same thing with sensor.potenza_leaf_combinata (which has the option display_zero: true): if I put it in the first position, it is no longer displayed and the space remains empty. 

I think there is some issue with the device sorting that interferes with the other options.

By(t)e
