### ISSUE TITLE
[SUPPORT] Inability of Home to display a sensor value, but the sensor can be displayed as secondary value

### ISSUE THREAD

**Issue by EPeterE** [flixlix/flixlix-cards#173]
Hi
I am not sure what I am doing wrong. I have created a sensor value "Home consumption" which is the power generated by the PV system subtracting the power from the battery. I require this since my invertor and controller uses power which is not recorded. So I would like the primary "Home" value to reflect the value of this sensor. However, the flow card doesn't display the value. The sensor can be displayed as a secondary value, but then the flow chart is incorrect since I assume it is based on the primary value. Is there anyway to correct this?
Just for clarity, the system is offgrid, so there should be no line from the BATTERY to the GRID either.

So in the evening, the PV generated is zero and the battery is discharging so the value for the Home Consumption sensor is 0--466W=466W and not the displayed value of 0. Due to the display showing 0, the flow card flow lines are wrong too.
![image](https://github.com/user-attachments/assets/c2cc89a2-ecf5-4061-92b3-22071a731f8b)
The secondary value is showing the sensor value correctly.
![image](https://github.com/user-attachments/assets/590cb52b-262a-482e-9d9e-6ab46a3c15dd)
And the sensor is created as a helper
![image](https://github.com/user-attachments/assets/739cd008-8d01-4c1e-9ad4-93586125a6d0)
Thanks

**Comment by lukasfichnaCGI** [comment]
Hi I have similar problem. I have set grid, solar and house consumption. When all power goes from solar then everything is ok, but when I take power from the grid I have 0 consumtion value in house and line between grid and house is greyed out. Consuption value is correctly showed as secondary value. I tried negate the consumption value also without luck.

![Image](https://github.com/user-attachments/assets/2d2c7e11-b872-4d2c-967c-03ad25916fb9)
```
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.helper_sum_of_import_power # value from image: -301
      production: sensor.helper_sum_of_export_power
    secondary_info: {}
  solar:
    entity: sensor.pv_power
    display_zero_state: true
  home:
    secondary_info:
      entity: sensor.house_consumption # value from image: 324
      unit_of_measurement: W
    entity: sensor.house_consumption # value from image: 324
    use_metadata: false
    override_state: false
    circle_animation: true
clickable_entities: true
display_zero_lines:
  mode: grey_out
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 6000
min_expected_power: 100
watt_threshold: 1000
transparency_zero_lines: 0
```
