### ISSUE TITLE
[FEATURE REQUEST + BUG]

### ISSUE THREAD

**Issue by IIIdefconIII** [flixlix/flixlix-cards#180]
**Describe the bug**

**Expected behavior**
See picture the Airco is 21 kWh which dhould w like in the picture
Same count for Cinema energy which shows kWh but the puicture also shows w
Anyway there working in the card now but it still s bit strange behaviour
As you can see there are also 3 devices of light which shows w. but i cant add more devices
A new entry left from mySup that woule be called Light would nice so i can put those 3 lights in there as its all culculated by watts.

**Screenshots**
![image](https://github.com/user-attachments/assets/a7127fe7-0970-443b-8a99-922245314368)

**Browser Console Errors**
no errors about this found

**Desktop (please complete the following information):**
Core
2024.9.1
Supervisor
2024.09.1
Operating System
13.1
Frontend
20240906.0

All in Chrome and its not a browser issue

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [ ] I have the latest version of the card installed.
yes

- [ ] I have cleared my browser cache **after** installing, updating and configuring the card.
yes

- [ ] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

```
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.v2266a_battery_power
    state_of_charge: sensor.terminal_ssh_cpu_percentage
    color_value: false
    invert_state: false
    use_metadata: false
    color_icon: true
  grid:
    entity: sensor.current_power_usage
    secondary_info: {}
    power_outage: {}
    name: Eneco
    color_icon: true
  individual:
    - entity: sensor.power_mysetup_power
      name: MySetup
      display_zero_state: true
      unit_of_measurement: w
      display_zero: true
      secondary_info: {}
      icon: hue:room-computer
      color_icon: true
    - entity: sensor.iiidefconiii_power_cinema_power
      name: Cinema
      display_zero_state: true
      calculate_flow_rate: false
      unit_of_measurement: w
      display_zero: true
      color_icon: true
      secondary_info: {}
    - entity: sensor.gas_meter
      name: Gas
      inverted_animation: false
      unit_white_space: true
      use_metadata: false
      show_direction: true
      icon: mdi:fire
      color_value: false
      color_icon: true
      color:
        - 255
        - 0
        - 0
      display_zero_state: false
      calculate_flow_rate: false
      display_zero: true
      unit_of_measurement: m3
      secondary_info: {}
    - entity: sensor.power_plug_airco_energy
      secondary_info: {}
      display_zero_state: true
      display_zero: true
      icon: mdi:air-conditioner
      name: A/C
      unit_of_measurement: w
      calculate_flow_rate: false
      decimals: 2
      color_icon: true
      color_value: false
  home:
    name: SkyNet
    icon: ''
    subtract_individual: false
    override_state: true
    secondary_info: {}
    color_icon: true
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 3
min_flow_rate: 0
max_flow_rate: 0
max_expected_power: 2000
min_expected_power: 0
watt_threshold: 2000
transparency_zero_lines: 0
title: SkyNet Power
card_mod:
  style: |
    ha-card {
    background: none !important;  
    border: none !important;
    }
```
