### ISSUE TITLE
[FEATURE REQUEST] Option to invert the Fossil Fuel percentage

### ISSUE THREAD

**Issue by i00** [flixlix/flixlix-cards#184]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like an option to invert the "fossil fuel percentage" from the grid. My electricity provider has a HA integration that has a "green energy" percent - so would be great if it could just accept that rather than me needing 2x sensors.

**Describe alternatives you've considered**
Adding a template sensor that inverses the value - but would be good if this was just an option

**Additional context**

**Comment by papperone** [comment]
+1 same for me, I think it's quite useful and we already have inverted value switch in the card for other entities...

**Comment by Leberkasbepi** [comment]
I have a fast solution for this. 

Go to the configuration.yaml file an input this lines

```
sensor:
  - platform: template
    sensors:
      korrigierter_fossiler_anteil:
        friendly_name: "Korrigierter Fossiler Anteil"
        unit_of_measurement: '%'
        value_template: "{{ 100 - (states('sensor.electricity_maps_anteil_fossiler_energietrager') | float) }}"

```

So the value is inverted and you can use it in the flow chart. "korrigierter_fossiler_anteil" is the name of your new sensor.
