### ISSUE TITLE
Remove the connecting line when power is below Display Zero Tolerance

### ISSUE THREAD

**Issue by stevedundee2** [flixlix/flixlix-cards#192]
**Is your feature request related to a problem? Please describe.**
It's not a problem, just a niche nice-to-have.

**Describe the solution you'd like**
Make the connecting line disappear when the current power goes below the Display Zero Tolerance. i.e. when power is as-good-as zero as well as when it is actually zero.

**Describe alternatives you've considered**
I could maybe use a Template to subtract the base power usage from the current usage (making sure it doesn't go negative), so that when it is idling then the value is zero. I'm not sure whether that is possible or would work. Or I could just live with it the way it is!

**Additional context**
In this image, the Battery and the Car are exchanging no power and so their connecting lines have nicely disappeared. For the Hot Water though, although the thermostat has turned it off and it is not actually heating water, there is always a small amount of power (4W-8W) being reported by the sensor. It's a solar diverter and I suppose it uses some power to monitor the system even if it is not actually heating water. I use Display Power Tolerance to hide this value, but the line remains. It would be nice if the line could disappear if the value is not being displayed due to the Display Power Tolerance (but be displayed when more power is being reported, as that means the water is being heated).

![image](https://github.com/flixlix/flixlix-cards/assets/57118112/5b44d1c0-41c5-47ea-93b6-cb0a7390878e)

**Comment by haysdb** [comment]
I've been fiddling trying to get the grid import/export to not display for small values, like < 50w, with no success. You're right that template sensors will fix this. Just what I need, two MORE template sensors. I swear, I literally have HUNDREDS.

**Comment by haysdb** [comment]
``` YAML
     # This sensor is for the Power Flow Card Plus so that the import/export lines don't show for small values
    - name: "Deye Grid Power Flow"
      unique_id: deye_grid_power_flow
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      availability: "{{ has_value('sensor.deye_grid_power') }}"
      state: >
        {% set val = states('sensor.deye_grid_power') | float %}
        {{ val if val | abs > 30 else 0 }}
```
