### ISSUE TITLE
Possibility to use the card for water or other non-electrical entities

### ISSUE THREAD

**Issue by Diavolezza** [flixlix/flixlix-cards#193]
It would be great if the card could also be used for the water flow. At the moment this is already possible, but always W or KW are used as measurement type (instead of e. g. Liters).

**Additional context**
This is my actual card including the water from outside and in- and outgoing of the cistern. Works fine, but how to remove the W?
![Bildschirmfoto 2024-05-10 um 11 51 56](https://github.com/flixlix/flixlix-cards/assets/8983765/e3d2f22a-36d9-4d1b-aa26-6386515a6731)

**Comment by SteadEXE** [comment]
I would love to get this feature working for water and maybe gaz if not using kW but m3?

**Comment by peter-dolkens** [comment]
Could you share your yaml for the above please @Diavolezza

**Comment by Diavolezza** [comment]
Sure. Here it is:
```
type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.home_consumption
    color_icon: solar
  grid:
    icon: mdi:water
    entity: sensor.stadtwasser_zulauf_active_water_usage
    display_state: one_way
    name: Stadtwasser
  battery:
    icon: mdi:water
    name: Zisterne
    entity:
      consumption: sensor.zisterne_zulauf_aktiver_wasserverbrauch
      production: sensor.zisterne_ablauf_aktiver_wasserverbrauch
    display_zero_state: true
    display_state: two_way
    state_of_charge: sensor.zisterne_inhalt_in_prozent
    color_circle: true
    color_value: false
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.9
max_flow_rate: 6
watt_threshold: 10000
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
disable_dots: false
use_new_flow_rate_model: false
```

**Comment by MaPaSoTo** [comment]
Hi,
I would like to follow up here, as the current solution does not work for me. Apart from that, "Zisterne" and "Stadtwasser" each have the unit "W", which cannot be correct here (and has also been mentioned).
I use the power flow card plus to display my water consumption as an individual source (under "Individual")

![Bildschirmfoto 2024-07-31 um 18 29 20](https://github.com/user-attachments/assets/9c5ccfc6-94fa-4d61-8fa5-36c006a4db2c)

This works quite well so far except for the fact that the consumption is displayed in litres and in cubic metres in the detailed view.

![Bildschirmfoto 2024-07-31 um 18 11 07](https://github.com/user-attachments/assets/00b11ae0-97a1-435a-8110-fa948df79e84)

Unfortunately, I can't see any way of correcting this in the overview. But maybe it will help someone :)

```
type: custom:power-flow-card-plus
entities:
  battery:
    entity:
      consumption: sensor.varta_output_power
      production: sensor.varta_input_power
    state_of_charge: sensor.mb_varta_soc
  grid:
    entity: sensor.smart_meter_summe_der_aktiven_momentanleistung
  solar:
    entity: sensor.pv_anlage_total_ausgangsleistung
    display_zero_state: true
    secondary_info:
      color_value: true
    use_metadata: true
    icon: ''
    name: PV-Leistung
  fossil_fuel_percentage:
    state_type: percentage
    entity: sensor.electricity_maps_anteil_fossiler_brennstoffe_im_netz
    color_value: false
    color_icon: true
    display_zero_state: false
    use_metadata: false
  individual:
    - entity: sensor.wallbox_charging_power
      name: wallbox
      icon: mdi:car
      color_value: false
      color_icon: false
      display_zero: true
      inverted_animation: false
      show_direction: true
      unit_of_measurement: ' W'
    - entity: sensor.softliq_d_bs50027353_current_flow_rate
      name: Wasser
      display_zero_state: true
      display_zero: true
      color_icon: false
      icon: mdi:water
      unit_of_measurement: Liter
      calculate_flow_rate: false
      inverted_animation: false
      show_direction: false
      unit_white_space: true
  home:
    entity: sensor.smart_meter_summe_der_aktiven_momentanleistung
    use_metadata: false
    override_state: false
    subtract_individual: false
    secondary_info:
      accept_negative: false
      unit_of_measurement: W
      decimals: 0
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
disable_dots: false
```
