### ISSUE TITLE
[BUG] Unable to display string from a template

### ISSUE THREAD

**Issue by lgm42** [flixlix/flixlix-cards#195]
Hello,
I' would like to indicate the color of the day (French Power provider). It can be Blue, White or Red.
An entity provide it to me into the entity: 'sensor.rte_tempo_couleur_actuelle'

![image](https://github.com/flixlix/flixlix-cards/assets/6039130/5d14ba15-fcf9-4f85-893a-875ea20c79ed)

I would like to see this string into the home circle as a secondary info

So I make following configuration:

```
entities:
  home:
    subtract_individual: false
    secondary_info:
      entity: sensor.rte_tempo_couleur_actuelle
      display_zero: true
      template: '{{states(''sensor.rte_tempo_couleur_actuelle''}}'
...
```
And I obtained Following result:

![image](https://github.com/flixlix/flixlix-cards/assets/6039130/463797d5-7ed3-4955-9109-c6b2753ea80c)

My information is marked as a javascript object: '[Object:object]', but the template home assistant tools says that it is a string.
Did I miss something ?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
