### ISSUE TITLE
[BUG]  "state_of_charge_unit_white_space: false"  completely ignored

### ISSUE THREAD

**Issue by mkanet** [flixlix/flixlix-cards#216]
Version:  v0.1.8.1

**Describe the bug**
I am trying to remove the whitespace between the state of charge value and state of charge unit for `Battery`.  Unfortunately, it is ignored.  I am not sure how else to do it

![image](https://github.com/flixlix/flixlix-cards/assets/811008/7b92432a-7e01-464b-aba3-d3455e1c00cf)

**To Reproduce**
```yaml
  battery:
    entity: sensor.mka_net_battery_power
    display_zero_tolerance: '10'
    state_of_charge: sensor.mka_net_charge
    state_of_charge_unit: '%'
    state_of_charge_unit_white_space: false  #This line is ignored!
    display_state: one_way
    color_state_of_charge_value: true
    color_icon: true
    color_circle: true
```

Below is my full card code, just in case something else in my code is interfering with the `state_of_charge_unit_white_space` setting.

```yaml
type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.mka_net_site_power
    display_zero_tolerance: '20'
    secondary_info:
      entity: sensor.pge_electric_cost_to_date
      unit_of_measurement: $
      unit_white_space: false
      color_value: true
    display_state: one_way
    color_circle: true
    color_icon: true
    color_value: true
    power_outage:
      entity: binary_sensor.mka_net_status
      state_alert: 'off'
  solar:
    entity: sensor.mka_net_solar_power
    display_zero_tolerance: '20'
    icon: mdi:solar-panel-large
    secondary_info:
      entity: sensor.openweathermap_cloud_coverage
      unit_of_measurement: '%'
      unit_white_space: false
      color_value: true
    color_icon: true
    color_value: true
  battery:
    entity: sensor.mka_net_battery_power
    display_zero_tolerance: '20'
    state_of_charge: sensor.mka_net_charge
    state_of_charge_unit: '%'
    state_of_charge_unit_white_space: false
    display_state: one_way
    color_state_of_charge_value: true
    color_icon: true
    color_circle: true
  home:
    entity: sensor.mka_net_load_power
    color_icon: true
    color_value: true
watt_threshold: 999
calculate_flow_rate: true
w_decimals: 1
kw_decimals: 1
min_flow_rate: 2.2
max_flow_rate: 6
display_zero_lines:
  mode: hide
clickable_entities: true
```
