### ISSUE TITLE
Separate entities for low and high tariff for grid consumption and production

### ISSUE THREAD

**Issue by vctrade** [flixlix/flixlix-cards#80]
P1 meters in the Netherlands do not report a total consumption or production but this is split into 

Consumption low
Consumption high
Production low
Production high

therefore only being able to select one consumption and one production is not the complete picture.

Many thanks I love the power and energy flow cards!

**Comment by StanAnsems** [comment]
@vctrade I think you might be able to fix this by adding both entities in a list.

```
type: custom:energy-flow-card-plus
entities:
  grid:
    entity:
      consumption:
        - sensor.electricity_meter_energieverbruik_tarief_2
        - sensor.electricity_meter_energieverbruik_tarief_1
      production:
        - sensor.electricity_meter_energieproductie_tarief_2
        - sensor.electricity_meter_energieproductie_tarief_1
````

Please correct me if i'm wrong?
