### ISSUE TITLE
[FEATURE REQUEST] Fossil fuel custom calculation

### ISSUE THREAD

**Issue by thomas-svrts** [flixlix/flixlix-cards#86]
**Is your feature request related to a problem? Please describe.**
In belgium we have the concept of energy sharing. This means that you can give away energy to whomever you want. 
I've set this up and I'm also tracking how much energy I received from my peers. As this 'free' energy also goes over the grid it's also measured there.
I tried to override the low carbon entity to populate it with the amount of free energy I got. But the entity for fossil fuel percentage is hardcoded to co2 Signal.

**Describe the solution you'd like**
The fossil fuel percentage 'entity' setting to be really used in frontend calculations and not only for "click-through" purposes.

  ```
fossil_fuel_percentage:
    show: true
    entity: sensor.energy_green_consumption
    color_value: false
    color_icon: false
    use_metadata: false
    state_type: power
    display_zero: false
    display_zero_state: false
    unit_white_space: true
    secondary_info:
      entity: sensor.groen_stroom_power
      unit_of_measurement: W
```

In fact roll back change https://github.com/flixlix/energy-flow-card-plus/pull/22

**Describe alternatives you've considered**
Creating a 3rd and 4th grid consumption entity (I already have consumption tarif1 and consumption tarif2) for the received 'free' energy during tarif1 and tarif2 periods. And then substract the received energy from the measured grid energy. But this is over complicating things.
And should do the same for production and energy I give away.

**Additional context**
